apiVersion: v1 
kind: Pod
metadata:
  name: web
  labels:
    env: production
    owner: iam
    webserver: nginx
    country: alg
spec:
  containers:
  - name: nginx
    image: nginx:1.22
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

